# we don't have static absolute path during build time
build:
  STATICFILES_STORAGE: 'whitenoise.storage.CompressedManifestStaticFilesStorage'
  STATIC_ROOT: 'kustosz/static/'
  STATICFILES_DIRS:
    - 'kustosz/staticfiles/'


production:
  STATICFILES_STORAGE: 'whitenoise.storage.CompressedManifestStaticFilesStorage'
  # we need to maintain the same list as default MIDDLEWARE,
  # with whitenoise injected in the middle
  MIDDLEWARE:
    - 'django.middleware.security.SecurityMiddleware'
    - 'corsheaders.middleware.CorsMiddleware'
    - 'whitenoise.middleware.WhiteNoiseMiddleware'
    - 'django.contrib.sessions.middleware.SessionMiddleware'
    - 'django.middleware.common.CommonMiddleware'
    - 'django.middleware.csrf.CsrfViewMiddleware'
    - 'django.contrib.auth.middleware.AuthenticationMiddleware'
    - 'django.contrib.messages.middleware.MessageMiddleware'
    - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  WHITENOISE_INDEX_FILE: True
  STATIC_ROOT: '/app/kustosz/static/'
  STATICFILES_DIRS:
    - '/app/kustosz/staticfiles/'
  KUSTOSZ_READABILITY_NODE_ENABLED: True
  CELERY_BROKER_URL: "filesystem://"
  CELERY_BROKER_TRANSPORT_OPTIONS:
    data_folder_out: '/app/kustosz/celery/queue'
    data_folder_in: '/app/kustosz/celery/queue'
    store_processed: False
